# Generated by Django 5.1.4 on 2025-01-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Kontakt')),
                ('description_before', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Vorher')),
                ('description_after', models.TextField(max_length=1000, verbose_name='Nachher')),
                ('start_year', models.IntegerField(default=2026, verbose_name='Von')),
                ('end_year', models.IntegerField(default=2025, verbose_name='Bis')),
                ('cost_plan_kchf', models.IntegerField(default=0, verbose_name='Kosten (kCHF)')),
                ('cost_effective_kchf', models.IntegerField(default=0)),
                ('effort_plan_pt', models.IntegerField(default=0)),
                ('duration_months', models.IntegerField(default=12)),
                ('progress', models.IntegerField(default=0)),
                ('process', models.IntegerField()),
                ('kompetence', models.IntegerField()),
                ('culture', models.IntegerField()),
                ('technology', models.IntegerField()),
                ('data', models.IntegerField()),
                ('legal', models.IntegerField()),
                ('employees', models.IntegerField(verbose_name='Mitarbeitende')),
                ('citizens', models.IntegerField(verbose_name='Bevölkerung')),
                ('economy', models.IntegerField(verbose_name='Wirtschaft')),
                ('verwendung_portal', models.BooleanField()),
            ],
        ),
    ]
