# Generated by Django 5.1.4 on 2025-01-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_internal_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='citizens',
            field=models.BooleanField(default=False, verbose_name='Bevölkerung'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cost_effective_kchf',
            field=models.IntegerField(default=0, verbose_name='Kosten ist (kCHF)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cost_plan_kchf',
            field=models.IntegerField(default=0, verbose_name='Budget (kCHF)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='culture',
            field=models.IntegerField(default=0, verbose_name='Kultur (1-5)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='data',
            field=models.IntegerField(default=0, verbose_name='Daten (1-5)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration_months',
            field=models.IntegerField(default=12, verbose_name='Dauer (Monate)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='economy',
            field=models.BooleanField(default=False, verbose_name='Wirtschaft'),
        ),
        migrations.AlterField(
            model_name='project',
            name='effort_plan_pt',
            field=models.IntegerField(default=0, verbose_name='Auwand Plan (kCHF)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='employees',
            field=models.BooleanField(default=False, verbose_name='Mitarbeitende'),
        ),
        migrations.AlterField(
            model_name='project',
            name='kompetence',
            field=models.IntegerField(default=0, verbose_name='Kompentenz (%)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='legal',
            field=models.IntegerField(default=0, verbose_name='Recht (1-5)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='process',
            field=models.IntegerField(default=0, verbose_name='Prozess (1-5)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.IntegerField(default=0, verbose_name='Fortschritt (%)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.IntegerField(default=0, verbose_name='TEchnologie 1-5)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='verwendung_portal',
            field=models.BooleanField(default=False, verbose_name='Portal'),
        ),
    ]
