# Generated by Django 5.1.4 on 2025-01-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_citizens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='decription',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cost_effective_kchf',
            field=models.IntegerField(default=0, verbose_name='Ist-Kosten (kCHF)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='effort_plan_pt',
            field=models.IntegerField(default=0, verbose_name='Aufwand Plan (PT)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='kompetence',
            field=models.IntegerField(default=0, verbose_name='Kompentenz (1-5)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.IntegerField(default=0, verbose_name='Technologie 1-5)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='verwendung_portal',
            field=models.BooleanField(default=False, verbose_name='Sichtbar in öff. Portal'),
        ),
    ]
