# Generated by Django 5.1.4 on 2025-01-18 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_url_alter_project_decription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Handlungsfeld')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Beschreibung')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Farbe')),
                ('icon', models.CharField(default='fas fa-cogs', max_length=50, verbose_name='Icon')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='kompetence',
        ),
        migrations.RemoveField(
            model_name='project',
            name='legal',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technology',
        ),
        migrations.AddField(
            model_name='project',
            name='infrastructure',
            field=models.IntegerField(default=0, verbose_name='Digitale Infrastruktur (1-5)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='culture',
            field=models.IntegerField(default=0, verbose_name='Trans\xadformation & Kulturwandel (1-5)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='process',
            field=models.IntegerField(default=0, verbose_name='Prozesse (1-5)'),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ziel')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Beschreibung')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Farbe')),
                ('icon', models.CharField(default='fas fa-bullseye', max_length=50, verbose_name='Icon')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.area', verbose_name='Handlungsfeld')),
            ],
        ),
    ]
