# Generated by Django 5.1.4 on 2025-01-18 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_area_remove_project_kompetence_remove_project_legal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='name',
            new_name='title',
        ),
    ]
