# Generated by Django 5.1.4 on 2025-01-18 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_name_area_title_rename_name_goal_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Beschreibung')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.goal', verbose_name='Ziel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Vorhaben')),
            ],
        ),
    ]
