# Generated by Django 5.1.4 on 2025-01-19 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectgoal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='decription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='goal',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_goals', to='projects.area', verbose_name='Handlungsfeld'),
        ),
        migrations.AlterField(
            model_name='projectgoal',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_projects', to='projects.goal', verbose_name='Ziel'),
        ),
    ]
